### ISSUE TITLE
Why you use `Addr` as keys in Maps?

### ISSUE THREAD

**Issue by pronvis** [CosmWasm/cw-plus#295]
Hey guys, thanks for your work! 
Have a little question :)
Why you use `Addr`(which is a String actually) as a key in Maps? [Here](https://github.com/CosmWasm/cosmwasm-plus/blob/65649f7f61ccae8504cb6cbb0c7cbd2c6a6ff3c2/contracts/cw20-base/src/state.rs#L33) for example?

[Here](https://docs.cosmwasm.com/0.14/architecture/addresses.html#optional-canonical-addresses) CosmWasm docs saying (and I agree):
```
This means that if message.signer is always the string address that signed
 the transaction and I use it to look up your account balance, if this encoding
 ever changed, then you lose access to your account. We clearly need
 a stable identifier to work with internally.
```

It is possible for address string representation to change, so ideally we all (smart contracts dev) should use `CanonicalAddr` as a key for Maps.

So, Why?

**Comment by ethanfrey** [comment]
Until Stargate, the Cosmos SDK stored addresses internally as raw bytes (CanonicalAddr) form.
We reflected and considered this would make sense if they changed bech32 prefix or decided to move to base58 or whatever.

However, since 0.40 the cosmos sdk uses bech32 encoding string addresses in all messages and in storage. Thus, it is near impossible to change the address encoding on a Cosmos SDK chain. Since that limits the runtime, we don't have to make all our contracts significantly more complex to handle cases the runtime doesn't support.

We also suggest using `Addr` in storage for 0.14 plus. This also means doing `addr_validate` on any address passed in via a message to ensure it is a legitimite address and not "random-text-here" which will fail later. Thus `pub fn addr_validate(&self, &str) -> Addr` on `deps.api`.

**Comment by ethanfrey** [comment]
We should update the cosmwasm docs for these new changes... Lots to do for 0.14 and 1.0 still...

**Comment by invis87** [comment]
Thanks much! 
Should I close this issue?

**Comment by ethanfrey** [comment]
No, leave it open. We need to improve the docs, then I will close it.
