### ISSUE TITLE
Iterate over historical data in SnapshotMap

### ISSUE THREAD

**Issue by archseer** [CosmWasm/cw-plus#487]
`SnapshotMap` currently provides `may_load_at_height`, but there's no such equivalent for `range`. Would it be possible to implement this? We're trying to iterate over historical data at a certain block height to see what the state was at the time.

**Comment by ethanfrey** [comment]
That is not possible with the current lazy data structures.

We make it very easy to range over `(Addr, height)`, but that means the data is stored such that `(height, Addr)` will require a brute force range.

> We're trying to iterate over historical data at a certain block height to see what the state was at the time.

You can do this externally with historical queries to gRPC/REST/Tendermint RPC (the underlying DB keeps history)

Can you give me the clear use case you have?
This can definitely be done in some cases (with limited data) if you take a real snapshot, rather than a zero-cost Copy-on-Write approach.

**Comment by ethanfrey** [comment]
In short, we cannot (and will not) implement this for SnapshotMap.
If this is a very clear requirement for your use case, I can advise for an alternative data structure that may fill your needs.
