### ISSUE TITLE
Update MIGRATING.md doc for multi test

### ISSUE THREAD

**Issue by ueco-jb** [CosmWasm/cw-plus#490]
https://github.com/CosmWasm/cw-plus/blob/main/packages/multi-test/MIGRATING.md

**Comment by ethanfrey** [comment]
@ueco-jb do you even remember what notes those were?

They were for migrating form 0.10 -> 0.11 or such I think, not sure if there are other changes. And at this point it probably doesn't matter to document a migration from anything older than 0.13 or 0.14. It would be good to check if we have any notes from those two release and maintain it, but otherwise just close.

**Comment by ueco-jb** [comment]
It's ancient history right now.

> And at this point it probably doesn't matter to document a migration from anything older than 0.13 or 0.14.

Agree, especially given that we didn't receive any requests about issues with migration.
I'll check CHANGELOG and update this issue if needed.

**Comment by ethanfrey** [comment]
Closing
