### ISSUE TITLE
Simple framework for gas benchmarking

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/cw-plus#507]
Gas usage benchmarking is a recurring topic, it would be nice to have simple utility for writing such benchmarks. It should be very simple to use, and with very much single responsibility - checking gas cost of performed calls. Under the hood real vm shall be used, with some help of its test utils, but benches on they own should not perform any verification (the behavior of contract is to be tested in UTs, and MTs, possibly some integration tests).

As a bonus it would be nice if the framework would report results in some common format, like json - it would make it probably much easier to integrate it with tools like grafana in future.

**Comment by maurolacy** [comment]
Benchmarking is in general a specific / punctual task. I mean, you usually want to measure the performance of some specific, isolated functionality.

For measuring the overall cost of execute, instantiate, etc. as we want to do in #505, perhaps a good option is to do it in a conventional way. That is, a CPU benchmark, in the context of a unit test (or multi-test). Instead of a gas usage benchmark, in the context of an integration test.

**Comment by uint** [comment]
@hashedone Is this really an `ng contracts`/Sylvia issue? This doesn't sound right

**Comment by JakeHartnell** [comment]
@de-husk implemented a framework, have a look: https://github.com/de-husk/cosm-orc
