### ISSUE TITLE
Implementation of hooks.rs (not) as `HashMap`

### ISSUE THREAD

**Issue by crnch** [CosmWasm/cw-plus#682]
Hi!
Getting to know the libraries while following TerraAcademy, I was wondering why hooks.rs is implemented as a `Vec` instead of an (allegedly more perfomant) `HashMap`. Any reasons I'm not seeing? If not, I'd be happy to reimplement :)

**Comment by ethanfrey** [comment]
HashMap is not serialisable with our json lib as ordering is not deterministic. Do not use it anywhere.

Also, since the process is "load struct from disk, deserialise, search", any performance gain HashMap would give would be offset by decreased performance of the deserialisation.

The other approach is to store in a `cw_storage_plus::Map`, but that uses a different key for every item, and is much more expensive if we always want to iterate over all items

**Comment by crnch** [comment]
thx @ethanfrey , I appreciate the explainnation! :+1:
