### ISSUE TITLE
Some multitest bindings for staking are missing such as `BondedDenom`

### ISSUE THREAD

**Issue by shanev** [CosmWasm/cw-plus#753]
This causes `deps.querier.query_bonded_denom()` to fail in mulitest.

**Comment by ethanfrey** [comment]
@shanev can you provide more details here, like a quick code sample to demo?

It can either be:
1. Building fully functional mocks for Staking (which is useful, but I would push to 0.16 not this release)
2. Export a few more missing types from multitest to allow a 3rd party to implement it (I would do this right away)

I know there was some other bug that someone couldn't build a multi-test mock for Distribution due to missing exports (it wasn't pub). We should check and address all those, maybe trying to build sample/failing mocks there in another module to show we have all types.

**Comment by ueco-jb** [comment]
> Building fully functional mocks for Staking (which is useful, but I would push to 0.16 not this release)

Some time ago I started tinkering around that.
https://github.com/CosmWasm/cw-plus/pull/782/files
It's kind of tricky to properly utilize tokens from Bank module storage, "temporary" I created own `STAKING` storage which acts as staked balances.

**Comment by ethanfrey** [comment]
Okay, then we just verify all types are exported. And close this, leaving some "future issue" for proper multi-test staking support

**Comment by maurolacy** [comment]
> Okay, then we just verify all types are exported. And close this, leaving some "future issue" for proper multi-test staking support

Regarding this, not exactly sure what needs to be done.

`BondedDenom` is published as part of `StakingQuery` in cosmwasm-std

https://github.com/CosmWasm/cosmwasm/blob/421f75cde11ff8842fd279ea3ec2cbcca65ef399/packages/std/src/query/staking.rs#L11-L34

along with the other staking queries.

The same with the staking messages

https://github.com/CosmWasm/cosmwasm/blob/421f75cde11ff8842fd279ea3ec2cbcca65ef399/packages/std/src/results/cosmos_msg.rs#L76-L90

What's required is implement the `Module` trait for staking in multitask, adding support for the staking messages and queries. But that's out of scope here. So, unless I'm missing something related to exporting these types, I would say, this is already done.

**Comment by ethanfrey** [comment]
@ueco-jb has started work on better testing in https://github.com/CosmWasm/cw-plus/pull/782

I assume this is what is desired (when finished)?
