### ISSUE TITLE
Make cw1155 can add token's url at the first mint

### ISSUE THREAD

**Issue by ALPAC-4** [CosmWasm/cw-plus#764]
There is no way to add url of cw1155 token despite it has [queryMsg](https://github.com/CosmWasm/cw-plus/blob/e360fed40b6148399337770324912bcdc518fa22/contracts/cw1155-base/src/contract.rs#L463-L466) for it.

**Comment by ethanfrey** [comment]
Huh, that contract is something of the orphan.

Since the CosmWasm core team has little to no understanding of the use cases of NFTs, we moved the nft code over to https://github.com/CosmWasm/cw-nfts

There is an open PR to add cw1155 there open for a long time: https://github.com/CosmWasm/cw-nfts/pull/27

Can you please follow up on that repo and see if they can update / maintain this (or volunteer to do so yourself)? There were too many demos, we trimmed down to the ones we could really maintain and let the community manage others.
